# Generated by Django 4.0.5 on 2022-06-27 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0002_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='full_name',
            field=models.CharField(max_length=50),
        ),
    ]
